spring:
    profiles:
    active:
    - dev
    
---      
spring:
    profiles: dev
    application:
        name: microservice-config-atguigu-dev
---  
spring:
    profiles:
    application:
        name: microservice-config-atguigu-test
    
    
    